syntax on
set hidden
set wildmenu
set showcmd
set hlsearch
set modeline
set ignorecase
set smartcase

set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set mouse=a

set shiftwidth=4
set softtabstop=4
set expandtab

map Y y$

