#!/bin/zsh 

alias -g ics='WDItemCostService'
alias -g als='WDLiquidationService'
alias -g liqwf='WDLiquidationWorkflow'
alias -g applog='application.log.`date -u +%F-%H`'
alias -g svclog='service_log.`date -u +%F-%H`'

function _bark {
    bark -ConfigFile=/home/user/.bark_$1
}

alias bark-dub='_bark dub'
alias bark-iad='_bark iad'
alias bark-sea='_bark sea'

alias reboothost='/opt/systems/bin/reboothost'

function gopkg() {
    ws $1
    cdpkg $2
}

function activate() {
    sudo runCommand -a Activate -e $1
}

function post-review() {
    /apollo/env/SDETools/bin/post-review --note --target-groups goldfish-dev $@
}

