#!/bin/zsh

APOLLO_API_URL="http://apollo-environment.amazon.com"

function find-envs() {
    recs-fromatomfeed "$APOLLO_API_URL/environmentStages?nameSubstring=$1" | 
        recs-eval '{{title}}'
}

function find-envs-by-package() {
    url="$APOLLO_API_URL/environmentStages?package=$1"
    if [[ ! -z "$2" ]]; then
        url="$url&stage=$2"
    fi

    echo $url
    recs-fromatomfeed "$url" |
        recs-eval '{{title}}'
}

function find-hosts-by-env() {
    recs-fromatomfeed "$APOLLO_API_URL/environmentStages/$1/-/cachedCapacity" |
    recs-eval '{{title}}'
}
